# Generated by Django 5.2.10 on 2026-02-09 15:14

import hopin_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', hopin_app.models.UserManager()),
            ],
        ),
    ]
