# Generated by Django 5.2.10 on 2026-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=254)),
                ('userpassword', models.CharField(max_length=50)),
                ('useraccess', models.CharField(default='allowed')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
