# Generated by Django 5.2.10 on 2026-02-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='useredetail',
            new_name='userdetail',
        ),
    ]
