# Generated by Django 5.2.10 on 2026-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0002_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.CharField(default='0'),
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.CharField(default='0'),
        ),
    ]
