# Generated by Django 5.2.10 on 2026-02-02 15:43

import hopin_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0002_user_delete_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userpassword',
            new_name='hashedpassword',
        ),
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
