# Generated by Django 5.2.10 on 2026-02-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0003_rename_useredetail_userdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='useraccess',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='payment_pending',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
