# Generated by Django 5.2.10 on 2026-03-04 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0003_trip_latitude_trip_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route',
        ),
        migrations.AddField(
            model_name='trip',
            name='routegeometry',
            field=models.JSONField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
