# Generated by Django 5.2.10 on 2026-02-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0003_rename_userpassword_user_hashedpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
