# Generated by Django 5.2.10 on 2026-02-12 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0004_remove_userdetail_useraccess_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='payment_pending',
            new_name='paymentpending',
        ),
        migrations.CreateModel(
            name='driverdetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preferedlocation', models.CharField()),
                ('prefereddirection', models.CharField()),
                ('vehiclenumber', models.CharField(max_length=12)),
                ('vehicletype', models.CharField()),
                ('vehiclemodel', models.CharField()),
                ('usercredentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
