# Generated by Django 5.2.10 on 2026-02-16 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0005_rename_payment_pending_userdetail_paymentpending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='viaroute',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
