# Generated by Django 5.2.10 on 2026-03-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0005_alter_trip_routegeometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='routegeometry',
            field=models.JSONField(null=True, blank=True),
        ),
    ]
