# Generated by Django 5.2.10 on 2026-02-08 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0005_useredetails_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='useredetails',
            new_name='useredetail',
        ),
    ]
