# Generated by Django 5.2.10 on 2026-02-21 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0006_driverdetail_viaroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetail',
            name='usercredentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
