# Generated by Django 5.2.10 on 2026-03-05 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0007_alter_trip_routegeometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='riderequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riderdetails', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripdetails', to='hopin_app.trip')),
            ],
        ),
    ]
