# Generated by Django 5.2.10 on 2026-02-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0007_alter_driverdetail_usercredentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdetail',
            old_name='viaroute',
            new_name='route',
        ),
    ]
