# Generated by Django 5.2.10 on 2026-03-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('hopin_app', '0008_riderequest'),
    ]

    operations=[
        migrations.AddField(
            model_name='trip',
            name='availableseats',
            field=models.CharField(blank=True, null=True),
        ),
    ]
