# Generated by Django 5.2.10 on 2026-03-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0009_trip_availableseats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='availableseats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
