# Generated by Django 5.2.10 on 2026-03-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('hopin_app', '0010_alter_trip_availableseats'),
    ]

    operations=[
        migrations.AddField(
            model_name='trip',
            name='ridedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='ridetime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
