# Generated by Django 5.2.10 on 2026-03-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0011_trip_ridedate_trip_ridetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='riderequest',
            unique_together={('trip', 'rider')},
        ),
    ]
