# Generated by Django 5.2.10 on 2026-03-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0012_alter_riderequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='availableseats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ridedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ridetime',
            field=models.TimeField(),
        ),
    ]
