# Generated by Django 5.2.10 on 2026-03-08 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0013_alter_trip_availableseats_alter_trip_ridedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='usercredentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
