# Generated by Django 5.2.10 on 2026-03-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('hopin_app', '0014_alter_trip_usercredentials'),
    ]

    operations=[
        migrations.AddField(
            model_name='trip',
            name='currentlatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='currentlongitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
