# Generated by Django 5.2.10 on 2026-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0015_trip_currentlatitude_trip_currentlongitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lastlocationupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
