# Generated by Django 5.2.10 on 2026-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('hopin_app', '0016_trip_lastlocationupdate'),
    ]

    operations=[
        migrations.AddField(
            model_name='riderequest',
            name='pickuplatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickuplongitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
