# Generated by Django 5.2.10 on 2026-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0017_riderequest_pickuplatitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(default='EMPTY'),
        ),
    ]
