# Generated by Django 5.2.10 on 2026-03-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('hopin_app', '0018_alter_trip_status'),
    ]

    operations=[
        migrations.AddField(
            model_name='trip',
            name='has_boarded',
            field=models.BooleanField(default=False),
        ),
    ]
