# Generated by Django 5.2.10 on 2026-03-17 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0019_trip_has_boarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='usercredentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
