# Generated by Django 5.2.10 on 2026-03-18 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('hopin_app', '0020_alter_trip_usercredentials'),
    ]

    operations=[
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='PENDING')),
                ('orderid', models.CharField(blank=True, null=True)),
                ('paymentid', models.CharField(blank=True, null=True)),
                ('requestdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopin_app.riderequest')),
            ],
        ),
    ]
