# Generated by Django 5.2.10 on 2026-03-20 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0022_alter_payment_requestdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='requestdetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tripdetails', to='hopin_app.riderequest'),
        ),
    ]
