# Generated by Django 5.2.10 on 2026-03-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('hopin_app', '0024_alter_payment_requestdetails'),
    ]

    operations=[
        migrations.AddField(
            model_name='riderequest',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
