# Generated by Django 5.2.10 on 2026-03-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0025_riderequest_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='averagerating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
