# Generated by Django 5.2.10 on 2026-03-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0026_userdetail_averagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
