# Generated by Django 5.2.10 on 2026-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0028_alter_userdetail_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
