# Generated by Django 5.2.10 on 2026-03-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies=[
        ('hopin_app', '0029_alter_userdetail_phonenumber'),
    ]

    operations=[
        migrations.RenameField(
            model_name='userdetail',
            old_name='paymentpending',
            new_name='verificationpending',
        ),
    ]
