# Generated by Django 5.2.10 on 2026-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0030_rename_paymentpending_userdetail_verificationpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='helmet',
            field=models.CharField(blank=True, null=True),
        ),
    ]
