# Generated by Django 5.2.10 on 2026-03-22 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0031_trip_helmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='pickuplocation',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
