# Generated by Django 5.2.10 on 2026-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0032_riderequest_pickuplocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='pickuplocation',
            field=models.CharField(max_length=150),
        ),
    ]
