# Generated by Django 5.2.10 on 2026-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0033_alter_riderequest_pickuplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='price',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.FloatField(default=10),
        ),
    ]
