# Generated by Django 5.2.10 on 2026-03-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopin_app', '0034_riderequest_price_trip_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.FloatField(default=7.9),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.FloatField(),
        ),
    ]
